INSERT INTO apps (id, name, secret)
VALUES (1, 'test', '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIBsy7WzVtkQyqovkC7p9Viykz8dXj5QWNJYF+Jk9vdyjRoAoGCCqGSM49\nAwEHoUQDQgAE3kFVx+O5vktxtxSC7oyQZ8vP77+4XwC9z5cn8xLjRDN4ZdFONuH+\n6yFVvG1CGDRlLNxkRZx89oZCpkiS17L/7w==\n-----END EC PRIVATE KEY-----')
ON CONFLICT DO NOTHING;